# Generated by Django 2.1.3 on 2018-12-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='category',
            new_name='category_code',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('code', 'category_code')},
        ),
    ]
