# Generated by Django 2.1.3 on 2018-12-02 00:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0003_auto_20181201_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('code', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('name', models.CharField(max_length=64)),
                ('sentence', models.CharField(max_length=256)),
                ('category_code', models.ForeignKey(db_column='category_code', on_delete=django.db.models.deletion.CASCADE, to='data_storage.Category', to_field='code')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='content',
            name='category_code',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.AlterUniqueTogether(
            name='advice',
            unique_together={('category_code', 'code')},
        ),
    ]
