# Generated by Django 2.1.3 on 2018-12-02 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0004_auto_20181202_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advice',
            old_name='name',
            new_name='category',
        ),
    ]
