# Generated by Django 2.1.3 on 2018-12-02 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0005_auto_20181202_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advice',
            old_name='category',
            new_name='content',
        ),
    ]
