# Generated by Django 2.1.3 on 2018-12-08 01:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0006_auto_20181202_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineFriend',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=256, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField()),
                ('favorite_category_code', models.ForeignKey(db_column='favorite_category_code', on_delete=django.db.models.deletion.CASCADE, to='data_storage.Category', to_field='code')),
            ],
        ),
    ]
