# Generated by Django 2.1.3 on 2018-12-08 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0007_linefriend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linefriend',
            name='favorite_category_code',
            field=models.ForeignKey(db_column='favorite_category_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='data_storage.Category', to_field='code'),
        ),
        migrations.AlterField(
            model_name='linefriend',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
