# Generated by Django 2.1.3 on 2018-12-08 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0008_auto_20181208_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linefriend',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
