# Generated by Django 2.1.3 on 2018-12-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0009_auto_20181208_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='linefriend',
            name='asking',
            field=models.BooleanField(default=False),
        ),
    ]
