# Generated by Django 2.1.3 on 2018-12-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0010_linefriend_asking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='advice',
            name='category_code',
        ),
        migrations.RemoveField(
            model_name='linefriend',
            name='favorite_category_code',
        ),
        migrations.DeleteModel(
            name='Advice',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='LineFriend',
        ),
    ]
