# Generated by Django 2.1.3 on 2018-12-30 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='LineSession',
        ),
    ]
