# Generated by Django 2.1.3 on 2018-12-30 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='line_bot.LineFriend'),
        ),
    ]
