# Generated by Django 2.1.3 on 2018-12-30 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0003_auto_20181230_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='line_bot.LineFriend'),
        ),
    ]
