# Generated by Django 2.1.3 on 2018-12-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0003_auto_20181230_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linesession',
            name='id',
        ),
        migrations.AlterField(
            model_name='linesession',
            name='user_id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
